onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

minimumReleaseAge: 10080 # = 7 days
minimumReleaseAgeExclude:
  - '@types/**'
  - ts-type-forge
  - ts-data-forge
  - ts-fortress
  - ts-repo-utils
  - eslint-config-typed
  - octokit-safe-types
  - github-settings-as-code
