name: Lint Pull Request

on:
  pull_request_target:
    branches:
      - 'main'
      - 'release'
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  semantic-pull-request:
    name: Validate PR title
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: amannn/action-semantic-pull-request@fdd4d3ddf614fbcd8c29e4b106d3bbe0cb2c605d # v6.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
