name: Lint Pull Request

on:
  pull_request_target:
    branches:
      - 'main'
      - 'release'
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  semantic-pull-request:
    name: Validate PR title
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
